name: Lint and Run Test Suite

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python.
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  # TODO can we use real micropython for this?
  test-py34:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python.
      uses: actions/setup-python@v4
      with:
        python-version: '3.4.10'
    - name: Run test suite
      run: |
        python test.py

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run test suite
      run: |
        python test.py
